name: vmiso_example
description: Example of using VMISO
version: 1.0.0
author: Ryan Knell <rknell@snappyapps.com.au>
homepage: https://www.snappyapps.com.au

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vmiso:

flutter:
